services:
  spark:
    build: ./spark
    container_name: spark
    ports:
      - "8002:19888" 
    volumes:
      - ../data:/app/data
      - ../eda:/app/eda
      - ../tmp:/app/tmp
      - ../mlruns:/app/mlruns     
      - ../../tools:/app/tools
    env_file:
      - ./.env
    networks:
      - mynetwork

  mlflow:
    depends_on:
      - spark
    build: ./mlflow
    container_name: mlflow
    ports:
      - "15000:5000"
    volumes:
      - ../mlruns:/app/mlruns
    command: mlflow server --host 0.0.0.0 -p 5000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge