services:
  ui-st:
    build:
      context: .
      dockerfile: Dockerfile
    # command: ["streamlit", "run", "ui.py", "--server.port=45000", "--server.address=0.0.0.0"] # entrypoint
    ports:
      - "8501:8501" 
    volumes:
      - ../../data:/app/data
      - ../../tmp:/app/tmp
      - ../../mlruns:/app/mlruns     
      - ../../../tools:/app/tools
        
    entrypoint: ["streamlit", "run", "ui-st.py", "--server.port=8501", "--server.address=0.0.0.0", "--browser.gatherUsageStats", "false"]
    # entrypoint: ["streamlit", "run", "ui-st.py", "--server.port=8501", "--server.address=0.0.0.0"]
    
    # env_file:
    #   - ../.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


  