services:
  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501" 
    volumes:
        - ./content:/app/content
      # - ../../data:/app/data
      # - ../../tmp:/app/tmp
      # - ../../mlruns:/app/mlruns     
      # - ../../../tools:/app/tools
        
    entrypoint: ["streamlit", "run", "ui_st.py", "--server.port=8501", "--server.address=0.0.0.0", "--browser.gatherUsageStats", "false"]
    # entrypoint: ["streamlit", "run", "ui_st.py", "--server.port=8501", "--server.address=0.0.0.0"]
    
    # env_file:
    #   - ../.env
    networks:
      - mynetwork

  # gradio:
  #   build: ./gradio
  #   container_name: gradio
  #   ports:
  #     - "7860:7860" 
  #   volumes:
  #     - ./content:/app/content
  #     # - ../../data:/app/data
  #     # - ../../tmp:/app/tmp
  #     # - ../../mlruns:/app/mlruns     
  #     # - ../../../tools:/app/tools

  #   # env_file:
  #   #   - ../.env
  #   networks:
  #     - mynetwork

  #   # entrypoint: ["python", "ui-gr.py", "--server_name", "0.0.0.0", "--server_port", "7860"]
  #   entrypoint: ["python", "ui_gr.py"]



networks:
  mynetwork:
    driver: bridge


  