services:
  api:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000" 
    volumes:
      - ../data:/app/data
      - ../tmp:/app/tmp
      - ../mlruns:/app/mlruns     
      - ../../tools:/app/tools
    env_file:
      - ../.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge